version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb
    hostname: myhost
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./project:/usr/src/app
    ports:
      - "27017:27017"

  PostgreSQL:
    image: postgres:latest
    restart: always
    container_name: postgres
    hostname: myhost
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    volumes:
      - ./project:/usr/src/app
    ports:
      - "5432:5432"
